### ISSUE TITLE
Open up 2016 campaign page

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/rgsoc-campaign#27]
We also need to move the last two entries to the 2016 database (Exam Success from Sep 17 and Szymon Bluma on Sept 19th 2015).

Pinging @svenfuchs

**Comment by alicetragedy** [comment]
I see the Exam Success donation but not the other one. Could you check that this has been done @svenfuchs @anikalindtner and then close the issue accordingly? Thanks 👍
