### ISSUE TITLE
Share to Facebook is broken

### ISSUE THREAD

**Issue by plexus** [rails-girls-summer-of-code/rgsoc-campaign#3]
After making a donation, when clicking on the Facebook button, the dialog that pops up is mostly hidden, making it impossible to submit.

![2013-05-28-095509_1920x1080_scrot](https://f.cloud.github.com/assets/32212/571127/17854b5e-c76d-11e2-912b-9722483bbb87.png)

This is using Chromium (Chrome) v25 on Linux.

**Comment by sareg0** [comment]
hey @svenfuchs we're going through issues to see what has been fixed and what not. Did this every get attended to?

**Comment by svenfuchs** [comment]
@sareg0 i'm not sure, i would guess it didn't
